#!/usr/bin/env python3
import sys

# Default to 90 if no argument is passed
n = int(sys.argv[1]) if len(sys.argv) > 1 else 90

for i in range(1, n+1):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz", end=' ')
    elif i % 3 == 0:
        print("Fizz", end=' ')
    elif i % 5 == 0:
        print("Buzz", end=' ')
    else:
        print(i, end=' ')

